# Generated by Django 3.0.6 on 2020-05-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_version', models.CharField(max_length=6)),
                ('component_version', models.CharField(max_length=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_dashboard.Component')),
            ],
        ),
    ]
