# Generated by Django 3.0.6 on 2020-05-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='component_name',
            new_name='component_text',
        ),
    ]
