# Generated by Django 3.0.6 on 2020-05-10 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('version_dashboard', '0002_auto_20200510_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
