# Generated by Django 3.0.6 on 2020-05-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_dashboard', '0003_component_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='component_text',
            new_name='component_name',
        ),
        migrations.RemoveField(
            model_name='component',
            name='pub_date',
        ),
    ]
