# Generated by Django 3.0.6 on 2020-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='health_endpoint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
