# Generated by Django 3.0.6 on 2020-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_dashboard', '0002_auto_20200513_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environments',
            name='environment_type',
            field=models.CharField(blank=True, choices=[('DEV', 'Development'), ('SIT', 'Sit'), ('STAG', 'Staging'), ('PREP', 'Preproduction'), ('PROD', 'Production'), ('OTHERS', 'Others'), ('PREPA', 'Preproductiona'), ('PRODA', 'Productiona'), ('OTHERSA', 'Othersa')], max_length=10),
        ),
    ]
