# Generated by Django 3.0.6 on 2020-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_dashboard', '0004_auto_20200513_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='remarks',
            new_name='additional_details',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(choices=[('LOGIX', 'Logix'), ('EPM', 'Epm'), ('OCD', 'Ocd'), ('MESSAGING', 'Messaging'), ('PROMOTION_BROKER', 'Promotinbroker'), ('CUSTOMER_BROKER', 'Customerbroker')], max_length=20),
        ),
    ]
