# Generated by Django 3.0.6 on 2020-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_dashboard', '0005_auto_20200514_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='additional_details',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(choices=[('LOGIX', 'Logix'), ('EPM', 'Epm'), ('OCD', 'Ocd'), ('MESSAGING', 'Messaging'), ('PROMOTION_BROKER', 'Promotinbroker'), ('CUSTOMER_BROKER', 'Customerbroker')], max_length=30),
        ),
    ]
