# Generated by Django 3.0.6 on 2020-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_dashboard', '0006_auto_20200514_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(choices=[('LOGIX', 'Logix'), ('EPM', 'Epm'), ('OCD', 'Ocd'), ('MESSAGING', 'Messaging'), ('PROMOTION_BROKER', 'Promotinbroker'), ('CUSTOMER_BROKER', 'Customerbroker'), ('PDU_WRAPPER', 'Pduwrapper'), ('NR1_ADAPTER', 'Nr1Adapter'), ('COUPONS', 'Coupons'), ('LOYALTY', 'Loyalty'), ('REWARDS', 'Rewards'), ('PES', 'Pes'), ('IO_SERVER', 'Iosever'), ('PDU', 'Pdu')], max_length=30),
        ),
    ]
